### ISSUE TITLE
Ch05: Decoder Layer

### ISSUE THREAD

**Issue by RoyJevnisek** [thushv89/manning_tf2_in_action#36]
In chapter 5's decoder layer you define dec_attn_heads but never actually use it in the call. 

If I understand correctly the way to fix it is to:
1. add input to compute_multihead_output (the multi-head list)
2. adjust h1 and h2 accordingly.

**Comment by thushv89** [comment]
Hi @RoyJevnisek ,
Thanks for reporting this. I'll have a look and fix this.
